In [3]:
import math
import torch
import numpy as np
import torch.nn as nn

s = [
    # enc_input           dec_input         dec_output
    ['ich mochte ein bier P', 'S i want a beer .', 'i want a beer . E'],
    ['ich mochte ein cola P', 'S i want a coke .', 'i want a coke . E']
]

src_vocab = {'P': 0, 'ich': 1, 'mochte': 2, 'ein': 3, 'bier': 4, 'cola': 5}
tgt_vocab = {'P': 0, 'i': 1, 'want': 2, 'a': 3, 'beer': 4, 'coke': 5, 'S': 6, 'E': 7, '.': 8}


def f(sentences):
    enc_inputs, dec_inputs, dec_outputs = [], [], []
    for i in range(len(sentences)):
        enc_input = [[src_vocab[n] for n in sentences[i][0].split()]]  # [[1, 2, 3, 4, 0], [1, 2, 3, 5, 0]]
        dec_input = [[tgt_vocab[n] for n in sentences[i][1].split()]]  # [[6, 1, 2, 3, 4, 8], [6, 1, 2, 3, 5, 8]]
        dec_output = [[tgt_vocab[n] for n in sentences[i][2].split()]]  # [[1, 2, 3, 4, 8, 7], [1, 2, 3, 5, 8, 7]]

        # 这里extend()的作用：把input列表添加到inputs里面
        enc_inputs.extend(enc_input)
        dec_inputs.extend(dec_input)
        dec_outputs.extend(dec_output)

    # 注意这里需要是LongTensor
    # 默认Tensor得到32位浮点,LongTensor是得到64位长整数.
    return torch.LongTensor(enc_inputs), torch.LongTensor(dec_inputs), torch.LongTensor(
        dec_outputs)


for i in f(s):
    print(i)

tensor([[1, 2, 3, 4, 0],
        [1, 2, 3, 5, 0]])
tensor([[6, 1, 2, 3, 4, 8],
        [6, 1, 2, 3, 5, 8]])
tensor([[1, 2, 3, 4, 8, 7],
        [1, 2, 3, 5, 8, 7]])
