In [7]:
import torch
import torch.nn as nn

emb1 = nn.Embedding(8, 8)
src = torch.Tensor([1, 1, 4]).to(torch.int32)
print(src)
src_emb1 = emb1(src)
print(src_emb1.shape)
print(src_emb1)
src_emb_a = emb1(src)
print(src_emb_a)

tensor([1, 1, 4], dtype=torch.int32)
torch.Size([3, 8])
tensor([[ 1.2037,  1.1004,  0.6535,  0.2510, -0.4538,  0.8450, -0.6161,  0.4923],
        [ 1.2037,  1.1004,  0.6535,  0.2510, -0.4538,  0.8450, -0.6161,  0.4923],
        [-1.6123,  0.4479, -0.0403, -1.0696, -1.1404,  0.5549, -0.0828, -0.5015]],
       grad_fn=<EmbeddingBackward0>)
tensor([[ 1.2037,  1.1004,  0.6535,  0.2510, -0.4538,  0.8450, -0.6161,  0.4923],
        [ 1.2037,  1.1004,  0.6535,  0.2510, -0.4538,  0.8450, -0.6161,  0.4923],
        [-1.6123,  0.4479, -0.0403, -1.0696, -1.1404,  0.5549, -0.0828, -0.5015]],
       grad_fn=<EmbeddingBackward0>)


In [9]:
emb2 = nn.Embedding(8, 8)
src_emb2 = emb2(src)
print(src_emb2.shape)
print(src_emb2)
src_emb_b = emb2(src)
print(src_emb_b)

torch.Size([3, 8])
tensor([[-1.2133, -0.2942, -0.1236, -0.4316, -0.7831, -0.6311, -0.7604,  0.6508],
        [-1.2133, -0.2942, -0.1236, -0.4316, -0.7831, -0.6311, -0.7604,  0.6508],
        [-0.1822,  0.1492,  0.4124,  0.4931,  0.2398, -0.9877, -2.0619,  0.7228]],
       grad_fn=<EmbeddingBackward0>)
tensor([[-1.2133, -0.2942, -0.1236, -0.4316, -0.7831, -0.6311, -0.7604,  0.6508],
        [-1.2133, -0.2942, -0.1236, -0.4316, -0.7831, -0.6311, -0.7604,  0.6508],
        [-0.1822,  0.1492,  0.4124,  0.4931,  0.2398, -0.9877, -2.0619,  0.7228]],
       grad_fn=<EmbeddingBackward0>)
